### PR TITLE
Add optional title to showcase

### PR DESCRIPTION
**Pull request by krimin-killr21**
Added title capabilities. Adding a title will automatically dim the content text.

Ignored .imls and /.idea

Added a title to the main activity.

### CODE REVIEW

**Comment by krimin-killr21** [comment]
Also ignore my versioning. I'm just doing it so I can access my edits from other apps.

**Comment by sandro-csimas** [comment]
+1

**Comment by deano2390** [comment]
good stuff

**Comment by sandro-csimas** [comment]
This PR has a bug: #83

**Comment by haldertaer** [comment]
I really don't understand how I can use this new feature in my Android Studio project. I really got no idea... What are the steps to add optional title to showcase?

**Comment by turing-tech** [comment]
@haldertaer In the builder chain add

`.setTitleText("Hello")`

This will add a title.

**Pull request merged**
